package fr.tse.pri.parsers.graphicaltimeline;

/* Generated By:JavaCC: Do not edit this line. GraphicalTimeLineConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GraphicalTimeLineConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ODOUBLE_START = 11;
  /** RegularExpression Id. */
  int CDOUBLE_START = 12;
  /** RegularExpression Id. */
  int OR_START = 13;
  /** RegularExpression Id. */
  int WORDS_START = 14;
  /** RegularExpression Id. */
  int DATEALL_FROM = 17;
  /** RegularExpression Id. */
  int DATE_FROM = 18;
  /** RegularExpression Id. */
  int YEAR_FROM = 19;
  /** RegularExpression Id. */
  int SPECIAL_FROM = 20;
  /** RegularExpression Id. */
  int DATEALL_TO = 23;
  /** RegularExpression Id. */
  int DATE_TO = 24;
  /** RegularExpression Id. */
  int YEAR_TO = 25;
  /** RegularExpression Id. */
  int SPECIAL_TO = 26;
  /** RegularExpression Id. */
  int ODOUBLE_TEXT_IN = 34;
  /** RegularExpression Id. */
  int OR_TEXT_IN = 35;
  /** RegularExpression Id. */
  int WORDS_TEXT_IN = 36;
  /** RegularExpression Id. */
  int DATEALL_AT = 39;
  /** RegularExpression Id. */
  int DATE_AT = 40;
  /** RegularExpression Id. */
  int YEAR_AT = 41;
  /** RegularExpression Id. */
  int SPECIAL_AT = 42;
  /** RegularExpression Id. */
  int CDOUBLE_TEXTAT_IN = 48;
  /** RegularExpression Id. */
  int WORDS_TEXTAT_IN = 49;
  /** RegularExpression Id. */
  int UNEXPECTED_CHAR = 50;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int TIMELINE_START = 1;
  /** Lexical state. */
  int TIMELINE_FROM = 2;
  /** Lexical state. */
  int TIMELINE_TO = 3;
  /** Lexical state. */
  int TIMELINE_TEXT = 4;
  /** Lexical state. */
  int TIMELINE_TEXT_IN = 5;
  /** Lexical state. */
  int TIMELINE_AT = 6;
  /** Lexical state. */
  int TIMELINE_TEXTAT = 7;
  /** Lexical state. */
  int TIMELINE_TEXTAT_IN = 8;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<token of kind 2>",
    "<token of kind 3>",
    "<token of kind 4>",
    "<token of kind 5>",
    "<token of kind 6>",
    "<token of kind 7>",
    "<token of kind 8>",
    "<token of kind 9>",
    "\" \"",
    "\"[[\"",
    "\"]]\"",
    "\"|\"",
    "<WORDS_START>",
    "<token of kind 15>",
    "\" \"",
    "<DATEALL_FROM>",
    "<DATE_FROM>",
    "<YEAR_FROM>",
    "<SPECIAL_FROM>",
    "<token of kind 21>",
    "\" \"",
    "<DATEALL_TO>",
    "<DATE_TO>",
    "<YEAR_TO>",
    "<SPECIAL_TO>",
    "<token of kind 27>",
    "\"[[\"",
    "<token of kind 29>",
    "<token of kind 30>",
    "\" \"",
    "\"\\\'\"",
    "<token of kind 33>",
    "\"[[\"",
    "\"|\"",
    "<WORDS_TEXT_IN>",
    "<token of kind 37>",
    "\" \"",
    "<DATEALL_AT>",
    "<DATE_AT>",
    "<YEAR_AT>",
    "<SPECIAL_AT>",
    "<token of kind 43>",
    "\"[[\"",
    "<token of kind 45>",
    "<token of kind 46>",
    "\" \"",
    "\"]]\"",
    "<WORDS_TEXTAT_IN>",
    "<UNEXPECTED_CHAR>",
  };

}
